// Code generated by goctl. DO NOT EDIT.
// Source: makabaka.proto

package server

import (
	"context"

	"github.com/m4n5ter/makabaka/pb/makabaka"
	"github.com/m4n5ter/makabaka/rpc/makabaka/internal/logic/ping"
	"github.com/m4n5ter/makabaka/rpc/makabaka/internal/svc"
)

type PingServer struct {
	svcCtx *svc.ServiceContext
	makabaka.UnimplementedPingServer
}

func NewPingServer(svcCtx *svc.ServiceContext) *PingServer {
	return &PingServer{
		svcCtx: svcCtx,
	}
}

// Ping is a simple health check
func (s *PingServer) Ping(ctx context.Context, in *makabaka.PingRequest) (*makabaka.PingResponse, error) {
	l := pinglogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
