services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./temp/data/mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./temp/data/redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ./temp/data/meilisearch_data:/meili_data

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: brainrot
      MINIO_ROOT_PASSWORD: brainrot
    command: server /data --console-address ":9001"