// Code generated by goctl. DO NOT EDIT.
// Source: makabaka.proto

package server

import (
	"context"

	"github.com/m4n5ter/makabaka/pb/makabaka"
	"github.com/m4n5ter/makabaka/rpc/makabaka/internal/logic/article"
	"github.com/m4n5ter/makabaka/rpc/makabaka/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	makabaka.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

// Post article
func (s *ArticleServer) PostArticle(ctx context.Context, in *makabaka.PostArticleRequest) (*makabaka.PostArticleResponse, error) {
	l := articlelogic.NewPostArticleLogic(ctx, s.svcCtx)
	return l.PostArticle(in)
}

// Delete article
func (s *ArticleServer) DeleteArticle(ctx context.Context, in *makabaka.DeleteArticleRequest) (*makabaka.DeleteArticleResponse, error) {
	l := articlelogic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}
