// Code generated by goctl. DO NOT EDIT.
// Source: brainrot.proto

package server

import (
	"context"

	"brainrot/gen/pb/brainrot"
	"brainrot/rpc/brainrot/internal/logic/s3"
	"brainrot/rpc/brainrot/internal/svc"
)

type S3Server struct {
	svcCtx *svc.ServiceContext
	brainrot.UnimplementedS3Server
}

func NewS3Server(svcCtx *svc.ServiceContext) *S3Server {
	return &S3Server{
		svcCtx: svcCtx,
	}
}

// Get presigned url
func (s *S3Server) GetPresignedURL(ctx context.Context, in *brainrot.GetPresignedURLRequest) (*brainrot.GetPresignedURLResponse, error) {
	l := s3logic.NewGetPresignedURLLogic(ctx, s.svcCtx)
	return l.GetPresignedURL(in)
}
