// Code generated by goctl. DO NOT EDIT.
// Source: brainrot.proto

package server

import (
	"context"

	"brainrot/gen/pb/brainrot"
	"brainrot/rpc/brainrot/internal/logic/user"
	"brainrot/rpc/brainrot/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	brainrot.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Sign up
func (s *UserServer) SignUp(ctx context.Context, in *brainrot.SignUpRequest) (*brainrot.SignUpResponse, error) {
	l := userlogic.NewSignUpLogic(ctx, s.svcCtx)
	return l.SignUp(in)
}

// Sign in
func (s *UserServer) SignIn(ctx context.Context, in *brainrot.SignInRequest) (*brainrot.SignInResponse, error) {
	l := userlogic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}

// Update user
func (s *UserServer) Update(ctx context.Context, in *brainrot.UpdateUserRequest) (*brainrot.UpdateUserResponse, error) {
	l := userlogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// Search users
func (s *UserServer) Search(ctx context.Context, in *brainrot.SearchUsersRequest) (*brainrot.SearchUsersResponse, error) {
	l := userlogic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

// Refresh token
func (s *UserServer) RefreshToken(ctx context.Context, in *brainrot.RefreshTokenRequest) (*brainrot.RefreshTokenResponse, error) {
	l := userlogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}
