// Code generated by goctl. DO NOT EDIT.
// Source: brainrot.proto

package article

import (
	"context"

	"brainrot/gen/pb/brainrot"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteArticleRequest     = brainrot.DeleteArticleRequest
	DeleteArticleResponse    = brainrot.DeleteArticleResponse
	Error                    = brainrot.Error
	MacFields                = brainrot.MacFields
	PingRequest              = brainrot.PingRequest
	PingResponse             = brainrot.PingResponse
	PostArticleRequest       = brainrot.PostArticleRequest
	PostArticleResponse      = brainrot.PostArticleResponse
	RefreshTokenRequest      = brainrot.RefreshTokenRequest
	RefreshTokenResponse     = brainrot.RefreshTokenResponse
	SearchUsersRequest       = brainrot.SearchUsersRequest
	SearchUsersResponse      = brainrot.SearchUsersResponse
	SearchUsersResponse_User = brainrot.SearchUsersResponse_User
	SignInRequest            = brainrot.SignInRequest
	SignInResponse           = brainrot.SignInResponse
	SignUpRequest            = brainrot.SignUpRequest
	SignUpResponse           = brainrot.SignUpResponse
	UpdateUserRequest        = brainrot.UpdateUserRequest
	UpdateUserResponse       = brainrot.UpdateUserResponse

	Article interface {
		// Post article
		PostArticle(ctx context.Context, in *PostArticleRequest, opts ...grpc.CallOption) (*PostArticleResponse, error)
		// Delete article
		DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

// Post article
func (m *defaultArticle) PostArticle(ctx context.Context, in *PostArticleRequest, opts ...grpc.CallOption) (*PostArticleResponse, error) {
	client := brainrot.NewArticleClient(m.cli.Conn())
	return client.PostArticle(ctx, in, opts...)
}

// Delete article
func (m *defaultArticle) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	client := brainrot.NewArticleClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}
