package articlelogic

import (
	"context"

	"github.com/m4n5ter/brainrot/pb/brainrot"
	"github.com/m4n5ter/brainrot/rpc/brainrot/internal/svc"

	"github.com/zeromicro/go-zero/core/logx"
)

type DeleteArticleLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	logx.Logger
}

func NewDeleteArticleLogic(ctx context.Context, svcCtx *svc.ServiceContext) *DeleteArticleLogic {
	return &DeleteArticleLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}

// Delete article
func (l *DeleteArticleLogic) DeleteArticle(in *brainrot.DeleteArticleRequest) (*brainrot.DeleteArticleResponse, error) {
	// todo: add your logic here and delete this line

	return &brainrot.DeleteArticleResponse{}, nil
}

// Generated by modified logic.tpl

// TODO: 设置一个 0~99 的唯一模块编号，以及模块名称
// var moduleNumberDeleteArticleLogic = merror.MustRegisterErrorModule(0, "DeleteArticleLogic")

// var ErrExample = merror.DefineError(merror.Common, moduleNumberDeleteArticleLogic, 10, "脱敏后的信息", "详细信息")
