// Code generated by goctl. DO NOT EDIT.
// Source: brainrot.proto

package ping

import (
	"context"

	"brainrot/gen/pb/brainrot"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteArticleRequest     = brainrot.DeleteArticleRequest
	DeleteArticleResponse    = brainrot.DeleteArticleResponse
	Error                    = brainrot.Error
	MacFields                = brainrot.MacFields
	PingRequest              = brainrot.PingRequest
	PingResponse             = brainrot.PingResponse
	PostArticleRequest       = brainrot.PostArticleRequest
	PostArticleResponse      = brainrot.PostArticleResponse
	RefreshTokenRequest      = brainrot.RefreshTokenRequest
	RefreshTokenResponse     = brainrot.RefreshTokenResponse
	SearchUsersRequest       = brainrot.SearchUsersRequest
	SearchUsersResponse      = brainrot.SearchUsersResponse
	SearchUsersResponse_User = brainrot.SearchUsersResponse_User
	SighInRequest            = brainrot.SighInRequest
	SighInResponse           = brainrot.SighInResponse
	SighUpRequest            = brainrot.SighUpRequest
	SighUpResponse           = brainrot.SighUpResponse
	UpdateUserRequest        = brainrot.UpdateUserRequest
	UpdateUserResponse       = brainrot.UpdateUserResponse

	Ping interface {
		// Ping is a simple health check
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	}

	defaultPing struct {
		cli zrpc.Client
	}
)

func NewPing(cli zrpc.Client) Ping {
	return &defaultPing{
		cli: cli,
	}
}

// Ping is a simple health check
func (m *defaultPing) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := brainrot.NewPingClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
