// Code generated by goctl. DO NOT EDIT.
// Source: brainrot.proto

package server

import (
	"context"

	"github.com/m4n5ter/brainrot/pb/brainrot"
	"github.com/m4n5ter/brainrot/rpc/brainrot/internal/logic/ping"
	"github.com/m4n5ter/brainrot/rpc/brainrot/internal/svc"
)

type PingServer struct {
	svcCtx *svc.ServiceContext
	brainrot.UnimplementedPingServer
}

func NewPingServer(svcCtx *svc.ServiceContext) *PingServer {
	return &PingServer{
		svcCtx: svcCtx,
	}
}

// Ping is a simple health check
func (s *PingServer) Ping(ctx context.Context, in *brainrot.PingRequest) (*brainrot.PingResponse, error) {
	l := pinglogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
